attack:
  pgd_order: skip
data:
  dataset: Customized("custom_model_data_calzone", "calzone_mnist", pixels_group=list(range(10)))
  end: 1
  mean: 0.0
  start: 0
  std: 1.0
general:
  complete_verifier: skip
model:
  onnx_path: models/calzone/MNIST_convSmall_128_0.004_91_89_0.5_0.1.onnx
solver:
  alpha-crown:
    iteration: 100
    lr_alpha: 0.1
  batch_size: 10
  beta-crown:
    iteration: 20
    lr_alpha: 0.01
    lr_beta: 0.05
    lr_decay: 0.999
specification:
  epsilon: 0
  type: box
